<center><h1> IFT-6758  Data Science  </h1></center>
<center><h2> Automne - 2020 </h2></center> 
<center><h3> Labo - 3</h3></center> 
<center><h3> </h3></center> 
<center><h3> Pandas</h3></center>

In [ ]:
import pandas as pd

## EXERCISES

#### 1. Essayez de chargez le fichier `sample_data/california_housing_train.csv` dans un `DataFrame` et faire une exploration de données de base pour comprendre ces données.

In [ ]:
df = pd.read_csv("sample_data/california_housing_train.csv")

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           17000 non-null  float64
 1   latitude            17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   total_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB

In [ ]:
df.describe()

          longitude      latitude  ...  median_income  median_house_value
count  17000.000000  17000.000000  ...   17000.000000        17000.000000
mean    -119.562108     35.625225  ...       3.883578       207300.912353
std        2.005166      2.137340  ...       1.908157       115983.764387
min     -124.350000     32.540000  ...       0.499900        14999.000000
25%     -121.790000     33.930000  ...       2.566375       119400.000000
50%     -118.490000     34.250000  ...       3.544600       180400.000000
75%     -118.000000     37.720000  ...       4.767000       265000.000000
max     -114.310000     41.950000  ...      15.000100       500001.000000

[8 rows x 9 columns]

Déterminez s'il y a des NaNs dans ce dataframe.

In [ ]:
df.isnull().any().any()

False

Trouvez la population totale du Dataframe.

In [ ]:
df['population'].sum()

24302757.0

Retournez un Dataframe avec `*n*` éléments échantillonnés aléatoirement du DataFrame.

In [ ]:
n = 10
df.sample(n)

       longitude  latitude  ...  median_income  median_house_value
2898     -117.75     33.95  ...         7.5839            426900.0
5552     -118.17     33.97  ...         2.2422            168200.0
11732    -121.31     38.58  ...         2.5035            112500.0
7426     -118.35     33.93  ...         1.9766            162500.0
13181    -121.89     37.23  ...         8.1900            361600.0
14794    -122.20     37.43  ...         5.2391            500001.0
5591     -118.17     33.77  ...         2.1378            180400.0
7526     -118.36     33.96  ...         2.7284            146900.0
3731     -117.93     33.86  ...         2.6563            155000.0
2414     -117.57     33.90  ...         3.5525            137600.0

[10 rows x 9 columns]

Sélectionnez les rangées ou `housing_median_age` est en-dessous de 18 et `median_house_value` est au-dessus de 300,000.

In [ ]:
df.loc[(df['housing_median_age'] < 18) & (df['median_house_value'] > 300000)]

       longitude  latitude  ...  median_income  median_house_value
172      -116.26     33.65  ...        10.2948            382400.0
187      -116.33     33.72  ...         7.4382            353100.0
193      -116.37     33.69  ...         7.8005            318100.0
210      -116.42     33.76  ...         7.6281            341700.0
220      -116.44     33.74  ...         7.9885            403300.0
...          ...       ...  ...            ...                 ...
16520    -122.65     38.37  ...         5.7204            344100.0
16598    -122.71     38.50  ...         6.6104            330900.0
16672    -122.78     38.44  ...         3.9766            345300.0
16715    -122.85     38.37  ...         4.4437            305000.0
16776    -123.00     38.33  ...         5.6445            364800.0

[550 rows x 9 columns]

#### 2. Utilisons les données de ventes:

In [ ]:
import numpy as np
df = pd.DataFrame(np.random.random(size=(5, 3)))

How do you subtract the row mean from each element in the row?

In [ ]:
df.sub(df.mean(axis=1), axis=0)

          0         1         2
0  0.115780 -0.024459 -0.091321
1  0.044464  0.089632 -0.134096
2  0.121997 -0.354643  0.232646
3  0.207495  0.040767 -0.248262
4 -0.089483  0.493785 -0.404302

#### 3. How do you count how many unique rows a DataFrame has (i.e. ignore all rows that are duplicates)?

In [ ]:
# Given this dataframe
df = pd.DataFrame(np.random.randint(0, 2, size=(10, 3)))

len(df.drop_duplicates(keep=False))

4